Principal_amount=int(input("Enter principle amount: "))
Interest_rate=float(input('Enter Interest rate: '))
Number_of_years=float(input('Enter number of years: '))
Simple_Interest=float((Principal_amount*Interest_rate*Number_of_years)/100)
print("Simple interest= ",Simple_Interest)
